// ------------------------------------------------------------
// contract.rs — Afristore NFT Lending contract implementation
//

use soroban_sdk::{contract, contractimpl, Env};

/// NFT lending contract — replace this stub with the full implementation.
/// The `#[contract]` attribute also registers the Soroban panic handler,
/// which is required for `#![no_std]` WASM builds.
#[contract]
pub struct LendingContract;

#[contractimpl]
impl LendingContract {
    /// Placeholder so the crate compiles while the contract is being built.
    /// Remove this once the real entrypoints are in place.
    pub fn placeholder(_env: Env) -> u32 {
        0
    }
}

// LendingContractClient is generated by #[contractimpl] above and lives in
// this module automatically — no re-export needed.
