#![cfg(test)]

// ------------------------------------------------------------
// test.rs — Afristore NFT Lending contract tests
//

use soroban_sdk::Env;

use crate::contract::LendingContract;

/// Smoke test — verifies the contract deploys and the placeholder
/// entrypoint is callable. Remove once real entrypoints are implemented.
#[test]
fn test_contract_deploys() {
    let env = Env::default();
    let contract_id = env.register(LendingContract, ());

    // The client type is generated by #[contractimpl] as `LendingContractClient`
    // inside the `contract` module. Use the fully-qualified path until
    let client = crate::contract::LendingContractClient::new(&env, &contract_id);
    assert_eq!(client.placeholder(), 0);
}
